### ISSUE TITLE
Touch area in TextView

### ISSUE THREAD

**Issue by felipeborba-dev** [n4kz/react-native-material-textfield#248] opened 2020-04-01 17:04 UTC
The TextField touch area is considering an area outside the field, I have attached an example gif

![2](https://user-images.githubusercontent.com/50309174/78165181-52cb0100-7421-11ea-88f6-e8616733c907.gif)

**Comment by Dina-Nashaat** [comment] 2020-04-05 13:46
possible duplicate of: https://github.com/n4kz/react-native-material-textfield/issues/199

**Closed as completed** 2020-04-08 23:47 UTC

**Comment by bbaoNg97** [comment] 2020-07-30 06:38
may i know whats the solution for this ya?
i also encountered this issue

**Comment by gaurav-psych** [comment] 2020-10-05 08:02
solution for this

**Comment by felipeborba-dev** [comment] 2020-10-05 14:29
I'm not using this lib anymore, I migrated to react-native-paper

**Comment by felipeborba-dev** [comment] 2020-10-05 14:31
This code can help

`labelTextStyle={{
position: 'absolute',
left: '100%'
}}`
